/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Frontend;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Jimenez
 */
public class FrmGraficos extends javax.swing.JFrame {
    
    boolean esValido=false;
    
    
    /**
     * Creates new form FrmGraficos
     */
    public FrmGraficos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPartido1 = new javax.swing.JLabel();
        lblPartido2 = new javax.swing.JLabel();
        lblPartido3 = new javax.swing.JLabel();
        txtPartido1 = new javax.swing.JTextField();
        txtPartido2 = new javax.swing.JTextField();
        txtPartido3 = new javax.swing.JTextField();
        btnGraficar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPartido1.setText("lPartido1");

        lblPartido2.setText("Partido2");

        lblPartido3.setText("Partido3");

        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPartido2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPartido2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPartido1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPartido1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPartido3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGraficar)
                            .addComponent(txtPartido3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPartido1)
                            .addComponent(txtPartido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblPartido2))
                    .addComponent(txtPartido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPartido3)
                    .addComponent(txtPartido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGraficar)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        // TODO add your handling code here:
        esValido=true;
        repaint();
        
    }//GEN-LAST:event_btnGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGraficos().setVisible(true);
            }
        });
    }
    
    /*public void paint(Graphics g)
    {
        super.paint(g);
        if(esValido)
        {
            int valor1=Integer.parseInt(txtPartido1.getText());
            int valor2=Integer.parseInt(txtPartido2.getText());
            int valor3=Integer.parseInt(txtPartido3.getText());
            int suma=valor1+valor2+valor3;
            int grados1=valor1*360/suma;
            int grados2=valor2*360/suma;
            int grados3=valor3*360/suma;
            
            g.setColor(new Color(255,0,0));
            g.fillArc(50,250,200,200,0,grados1);
            g.fillRect(370,250,20,20);
            g.drawString("Partido 1", 400, 270);            

            g.setColor(new Color(0,128,0));
            g.fillArc(50,250,200,200,grados1,grados2);
            g.fillRect(370,280,20,20);
            g.drawString("Partido 2", 400, 300);            

            g.setColor(new Color(0,0,255));
            g.fillArc(50,250,200,200,grados1+grados2,grados3);
            g.fillRect(370,310,20,20);
            g.drawString("Partido 3", 400, 330);
            
            
        }
    
    }*/
    
  /*  public void paint(Graphics g)
    {
        super.paint(g);
        if(esValido)
        {
            int valor1=Integer.parseInt(txtPartido1.getText());
            int valor2=Integer.parseInt(txtPartido2.getText());
            int valor3=Integer.parseInt(txtPartido3.getText());
            int mayor=retornarMayor(valor1, valor2, valor3);
            
            int largo1=valor1*400/mayor;
            int largo2=valor2*400/mayor;
            int largo3=valor3*400/mayor;
            
            g.setColor(new Color(255,0,0));
            g.fillRect(100,250,largo1,40);
            g.drawString("Partido 1", 10, 270);            

            g.setColor(new Color(0,128,0));
            g.fillRect(100,300,largo2,40);
            g.drawString("Partido 2", 10, 320);            

            g.setColor(new Color(0,0,255));
            g.fillRect(100,350,largo3,40);
            g.drawString("Partido 3", 10, 370); 
        }
    }*/
    
    
     public void paint(Graphics g)
    {
        super.paint(g);
        if(esValido)
        {
            int valor1=Integer.parseInt(txtPartido1.getText());
            int valor2=Integer.parseInt(txtPartido2.getText());
            int valor3=Integer.parseInt(txtPartido3.getText());
       
            int suma=valor1+valor2+valor3;
            int largo1=valor1*400/suma;
            int largo2=valor2*400/suma;
            int largo3=valor3*400/suma;
            
            int porc1=valor1*100/suma;
            int porc2=valor2*100/suma;
            int porc3=valor3*100/suma;   
            
             g.setColor(new Color(255,0,0));
            g.fillRect(50,250,largo1,50);
            g.setColor(new Color(255,255,255));
            g.drawString(porc1+"%",55,270);
            
            g.setColor(new Color(0,128,0));
            g.fillRect(50+largo1,250,largo2,50);
            g.setColor(new Color(255,255,255));
            g.drawString(porc2+"%",55+largo1,270);
            
            
            g.setColor(new Color(0,0,255));
            g.fillRect(50+largo1+largo2,250,largo3,50);
            g.setColor(new Color(255,255,255));
            g.drawString(porc3+"%",55+largo1+largo2,270);
        }
    }
    
    
     private int retornarMayor(int v1,int v2,int v3)
    {
        if (v1>v2 && v1>v3)
            return v1;
        else
            if (v2>v3)
                return v2;
            else
                return v3;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.JLabel lblPartido1;
    private javax.swing.JLabel lblPartido2;
    private javax.swing.JLabel lblPartido3;
    private javax.swing.JTextField txtPartido1;
    private javax.swing.JTextField txtPartido2;
    private javax.swing.JTextField txtPartido3;
    // End of variables declaration//GEN-END:variables
}
